version: "3.8"

services:
  
  #react service
  react:
    container_name: pokedex
    build:
      context: ./docker/react

    volumes:
      - ./app:/appclient

    ports:
      - '3000:3000'

    environment:
      - CHOKIDAR_USEPOLLING=true

    tty: true