version: "3.8"

services:
  
  #react service
  react:
    container_name: client
    build:
      context: ./docker/react

    ports:
      - '3000:3000'

    environment:
      - CHOKIDAR_USEPOLLING=true

    tty: true